"""PGN / FEN / SAN parsing pipeline.

Split from ``mcp_server.server`` for navigability. Five modules cover the
parsing stages:

- :mod:`mcp_server.parsers.pgn_sanitize` — strip conversational PGN cruft.
- :mod:`mcp_server.parsers.pgn_canonical` — canonical PGN extraction.
- :mod:`mcp_server.parsers.pgn_validate` — variant / TimeControl / FEN validators.
- :mod:`mcp_server.parsers.board_builder` — FEN / PGN / movetext → ``chess.Board``.
- :mod:`mcp_server.parsers.move_parser` — SAN / UCI move parsing.
"""

from mcp_server.parsers.board_builder import (
    _build_board,
    _build_board_with_metadata,
    _history_provenance_for_input,
    build_board,
    build_board_with_metadata,
    history_provenance_for_input,
)
from mcp_server.parsers.move_parser import (
    _parse_move_on_board,
    _parse_move_on_board_with_warning,
    parse_move_on_board,
    parse_move_on_board_with_warning,
)
from mcp_server.parsers.pgn_canonical import (
    FIGURINE_MAP,
    TAG_PAIR_REGEX,
    UNICODE_HYPHEN_MAP,
    _FIGURINE_MAP,
    _UNICODE_HYPHEN_MAP,
    _check_multiple_games,
    _clean_conversational_text,
    _extract_canonical_pgn_text,
    _extract_game,
    _extract_game_inner,
    _find_movetext_result,
    _has_completed_game_before,
    _infer_result_from_termination,
    _is_canonical_tag_line,
    _is_prose_line,
    _normalize_multiline_tags,
    _normalize_movetext_figurines,
    _normalize_unicode_pgn_results,
    _parse_pgn_game_candidate,
    _sanitize_malformed_pgn_header_lines,
    _strip_promotion_eq,
    _strict_top_level_movetext_tokens,
    _truncate_movetext_at_result,
    _validate_movetext_tokens,
    _validate_strict_header_syntax,
    _validate_strict_mainline_surface,
    check_multiple_games,
    clean_conversational_text,
    extract_canonical_pgn_text,
    extract_game,
    extract_game_inner,
    find_movetext_result,
    has_completed_game_before,
    infer_result_from_termination,
    is_canonical_tag_line,
    is_prose_line,
    normalize_multiline_tags,
    normalize_movetext_figurines,
    normalize_unicode_pgn_results,
    parse_pgn_game_candidate,
    sanitize_malformed_pgn_header_lines,
    strip_promotion_eq,
    strict_top_level_movetext_tokens,
    truncate_movetext_at_result,
    validate_movetext_tokens,
    validate_strict_header_syntax,
    validate_strict_mainline_surface,
)
from mcp_server.parsers.pgn_sanitize import (
    TAG_PAIR_REGEX as _TAG_PAIR_REGEX_FROM_SANITIZE,
    _mask_comments_and_escapes,
    _sanitize_brackets_in_variations_and_comments,
    _strip_pgn_escape_lines,
    _unescape_pgn_tag_value,
    mask_comments_and_escapes,
    sanitize_brackets_in_variations_and_comments,
    strip_pgn_escape_lines,
    unescape_pgn_tag_value,
)
from mcp_server.parsers.pgn_validate import (
    SUPPORTED_VARIANTS,
    TIME_CONTROL_STAGE_RE,
    _is_valid_pgn_time_control,
    _stage_has_positive_number,
    _validate_castling_rights,
    _validate_fen_counters,
    _validate_pgn_date,
    _validate_variant,
    is_valid_pgn_time_control,
    stage_has_positive_number,
    validate_castling_rights,
    validate_fen_counters,
    validate_pgn_date,
    validate_variant,
)

__all__ = [
    # board_builder
    "build_board",
    "build_board_with_metadata",
    "history_provenance_for_input",
    "_build_board",
    "_build_board_with_metadata",
    "_history_provenance_for_input",
    # move_parser
    "parse_move_on_board",
    "parse_move_on_board_with_warning",
    "_parse_move_on_board",
    "_parse_move_on_board_with_warning",
    # pgn_canonical
    "FIGURINE_MAP",
    "TAG_PAIR_REGEX",
    "UNICODE_HYPHEN_MAP",
    "_FIGURINE_MAP",
    "_UNICODE_HYPHEN_MAP",
    "check_multiple_games",
    "clean_conversational_text",
    "extract_canonical_pgn_text",
    "extract_game",
    "extract_game_inner",
    "find_movetext_result",
    "has_completed_game_before",
    "infer_result_from_termination",
    "is_canonical_tag_line",
    "is_prose_line",
    "normalize_multiline_tags",
    "normalize_movetext_figurines",
    "normalize_unicode_pgn_results",
    "parse_pgn_game_candidate",
    "sanitize_malformed_pgn_header_lines",
    "strip_promotion_eq",
    "strict_top_level_movetext_tokens",
    "truncate_movetext_at_result",
    "validate_movetext_tokens",
    "validate_strict_header_syntax",
    "validate_strict_mainline_surface",
    "_check_multiple_games",
    "_clean_conversational_text",
    "_extract_canonical_pgn_text",
    "_extract_game",
    "_extract_game_inner",
    "_find_movetext_result",
    "_has_completed_game_before",
    "_infer_result_from_termination",
    "_is_canonical_tag_line",
    "_is_prose_line",
    "_normalize_multiline_tags",
    "_normalize_movetext_figurines",
    "_normalize_unicode_pgn_results",
    "_parse_pgn_game_candidate",
    "_sanitize_malformed_pgn_header_lines",
    "_strip_promotion_eq",
    "_strict_top_level_movetext_tokens",
    "_truncate_movetext_at_result",
    "_validate_movetext_tokens",
    "_validate_strict_header_syntax",
    "_validate_strict_mainline_surface",
    # pgn_sanitize
    "mask_comments_and_escapes",
    "sanitize_brackets_in_variations_and_comments",
    "strip_pgn_escape_lines",
    "unescape_pgn_tag_value",
    "_mask_comments_and_escapes",
    "_sanitize_brackets_in_variations_and_comments",
    "_strip_pgn_escape_lines",
    "_unescape_pgn_tag_value",
    # pgn_validate
    "SUPPORTED_VARIANTS",
    "TIME_CONTROL_STAGE_RE",
    "is_valid_pgn_time_control",
    "stage_has_positive_number",
    "validate_castling_rights",
    "validate_fen_counters",
    "validate_pgn_date",
    "validate_variant",
    "_is_valid_pgn_time_control",
    "_stage_has_positive_number",
    "_validate_castling_rights",
    "_validate_fen_counters",
    "_validate_pgn_date",
    "_validate_variant",
]
