from pathlib import Path

path = Path(__file__).resolve().parents[1] / "tests/test_mcp_server.py"
text = path.read_text(encoding="utf-8")
old = '''@pytest.mark.asyncio\nasync def test_audit_12_mcp_eval_history_dependent_status():\n    """Item 12 / Bug 7: 50-move rule status is in FEN (requires_move_stack=False, lichess reproduces=True); repetition requires move stack."""\n    # Active board without repetition/50-move -> history_dependent_status is False, lichess_url_reproduces_history is True\n    b = chess.Board()\n    b.push_san("e4")\n    b.push_san("e5")\n    ev = MCPEval.from_eval(Eval(cp=20, best_move="g1f3", pv=["g1f3"], depth=14), b.fen(), board=b)\n    assert ev.history_dependent_status is False\n    assert ev.lichess_url_reproduces_history is True\n    assert ev.requires_move_stack is False\n    assert ev.fen_sufficient_for_status is True\n\n    # 50-move rule claimable -> halfmove clock in FEN, history_dependent_status is False, lichess reproduces=True\n    b_50 = chess.Board()\n    b_50.halfmove_clock = 100\n    ev_50 = MCPEval.from_eval(Eval(cp=0, best_move="e2e4", pv=["e2e4"], depth=14), b_50.fen(), board=b_50)\n    assert ev_50.history_dependent_status is False\n    assert ev_50.lichess_url_reproduces_history is True\n    assert ev_50.requires_move_stack is False\n    assert ev_50.fen_sufficient_for_status is True\n'''
new = '''@pytest.mark.asyncio\nasync def test_audit_12_mcp_eval_history_dependent_status():\n    """Incomplete FEN history must not pretend that repetition has been excluded."""\n    # A naked active FEN can prove board-local rules, but it cannot prove that\n    # no earlier repetition occurred. The response therefore explicitly asks\n    # for a move stack instead of claiming that the FEN reproduces all rule state.\n    b = chess.Board()\n    b.push_san("e4")\n    b.push_san("e5")\n    ev = MCPEval.from_eval(Eval(cp=20, best_move="g1f3", pv=["g1f3"], depth=14), b.fen(), board=b)\n    assert ev.repetition_status == "unknown"\n    assert ev.history_dependent_status is True\n    assert ev.lichess_url_reproduces_history is False\n    assert ev.requires_move_stack is True\n    assert ev.fen_sufficient_for_status is False\n\n    # The halfmove clock proves a 50-move claim from the FEN, but it still does\n    # not prove that threefold repetition is absent. Claimability is known; the\n    # complete set of history-dependent reasons is not.\n    b_50 = chess.Board()\n    b_50.halfmove_clock = 100\n    ev_50 = MCPEval.from_eval(Eval(cp=0, best_move="e2e4", pv=["e2e4"], depth=14), b_50.fen(), board=b_50)\n    assert "fifty_moves" in ev_50.claim_reasons_now\n    assert ev_50.repetition_status == "unknown"\n    assert ev_50.history_dependent_status is True\n    assert ev_50.lichess_url_reproduces_history is False\n    assert ev_50.requires_move_stack is True\n    assert ev_50.fen_sufficient_for_status is False\n'''
if old not in text:
    if new in text:
        print("history semantics regression already updated")
        raise SystemExit(0)
    raise SystemExit("expected history regression block not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("history semantics regression updated")
