"""Local in-memory 360-call stress matrix for Chess MCP.

Executes all 360 cases generated by scripts/production_stress_360.py directly
against server_module (evaluate_position, top_moves, classify_move, analyze_game),
validating response schemas, invariants, and catching any unexpected exceptions or errors.
"""

from __future__ import annotations

import asyncio
import sys
import time
from typing import Any

from mcp_server import server as server_module
from scripts.production_stress_360 import _build_case_iter


async def main() -> int:
    print("[INFO] Initializing analyzer pool...")
    pool = await server_module._get_analyzer_pool()
    print(f"[INFO] Pool ready: {pool.name}")

    tool_dispatch = {
        "evaluate_position": server_module.evaluate_position,
        "top_moves": server_module.top_moves,
        "classify_move": server_module.classify_move,
        "analyze_game": server_module.analyze_game,
    }

    cases = list(_build_case_iter())
    print(f"[INFO] Loaded {len(cases)} cases from production_stress_360 generator.")

    total = len(cases)
    passed = 0
    failed = 0
    errors: list[tuple[str, str, dict[str, Any], Exception]] = []

    t_start = time.monotonic()

    for idx, (tool_name, case_id, args) in enumerate(cases, 1):
        t0 = time.monotonic()
        func = tool_dispatch[tool_name]
        try:
            res = await func(**args)
            elapsed_ms = (time.monotonic() - t0) * 1000

            # Invariant checks:
            assert res is not None, "Response was None"

            # Basic invariants per tool
            if tool_name == "evaluate_position":
                assert hasattr(res, "status"), f"Missing status in {case_id}"
                assert hasattr(res, "best_action_obj"), f"Missing best_action_obj in {case_id}"
            elif tool_name == "top_moves":
                assert hasattr(res, "result"), f"Missing result in {case_id}"
                assert hasattr(res, "returned_n"), f"Missing returned_n in {case_id}"
            elif tool_name == "classify_move":
                assert hasattr(res, "move_class"), f"Missing move_class in {case_id}"
                assert hasattr(res, "action_class"), f"Missing action_class in {case_id}"
            elif tool_name == "analyze_game":
                assert hasattr(res, "total_plies"), f"Missing total_plies in {case_id}"

            passed += 1
            if idx % 30 == 0 or idx == total:
                print(
                    f"[{idx:03d}/{total}] {tool_name:<18} {case_id} OK ({elapsed_ms:.1f}ms) "
                    f"[cum: {time.monotonic() - t_start:.1f}s]"
                )
        except Exception as exc:
            elapsed_ms = (time.monotonic() - t0) * 1000
            err_text = str(exc)
            if any(marker in err_text for marker in ("INVALID_PGN", "INVALID_FEN", "OPPOSITE_CHECK", "INVALID_MOVE", "GAME_ALREADY_OVER")):
                passed += 1
                print(f"[{idx:03d}/{total}] {tool_name:<18} {case_id} EXPECTED_INVALID: {type(exc).__name__}: {exc}")
            else:
                failed += 1
                errors.append((tool_name, case_id, args, exc))
                print(f"[{idx:03d}/{total}] {tool_name:<18} {case_id} FAILED: {type(exc).__name__}: {exc}")

    total_time = time.monotonic() - t_start
    print("\n" + "=" * 60)
    print(f"STRESS MATRIX COMPLETED in {total_time:.2f}s")
    print(f"Total: {total}, Passed: {passed}, Failed: {failed}")
    print("=" * 60)

    await server_module.close_analyzer_pool()

    if failed > 0:
        print("\nSummary of failures:")
        for tool_name, case_id, args, exc in errors:
            print(f"- {tool_name} {case_id} with {args}: {type(exc).__name__}: {exc}")
        return 1

    print("\n[SUCCESS] All 360 stress calls passed without errors or invariant violations.")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
